name: Test

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: Install dependencies
              run: |
                  npm install
            - uses: ahwelgemoed/single-widget-build@main
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  author_name: JACKY
                  bot_commit_message: KILLING IT
                  bot_author_name: FUCKING BOTTY
                  bot_author_email: FUCKING@BOTTY.com
                  commit_message_trigger: publish new Package
                  packages_folder: packages
                  identify_widgets_folders: -widgets
